### ISSUE TITLE
Wrong URL listed on Meetup Info Page.

### ISSUE THREAD

**Issue by zipzit** [vegasjs/Website#14]
The meetup info page (located at: http://www.meetup.com/VegasJS/about/ ) shows website for the group as http://www.vegasjs.com/ 

(vegasjs.com shows up as a complete page in foreign language - Korean? Japanese?)

Actual website should be: http://javascript.vegas/

Anybody know how to fix the page at meetup.com?

**Comment by makenai** [comment]
Fixed, thank you!
