### ISSUE TITLE
Add talks for meetup #46

### ISSUE THREAD

**Issue by zpnk** [vegasjs/Website#20]
The talks for meetup #46 need to be added to the site. To do so, follow the [existing meetup format](https://github.com/vegasjs/Website/blob/master/index.html#L38-L43) and use the following data:
- Meetup date: 2015-12-15
- Meetup url: http://www.meetup.com/VegasJS/events/226892437/
- Talk 1: Mike Ziethlow - RPG Maker MV
  - Slides: http://www.rpgmakerweb.com/
- Talk 2: Jen Wilhelm - JavaScript Easter Eggs
  -  Code & slides: https://github.com/jenwilhelm/vegasjs_konami
- Talk 3: Dan Harden - ⛄️ as a Namespace
  - Slides: http://dharden.github.io/snowman.js/

If you would like to claim this ticket, comment below!

**Comment by jenwilhelm** [comment]
These have been added.
